{% set name = "ipyfastscape" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b5d5c18b18a4495a2fcac2f36a2048a955a99f0f51539cb439605a128df77974

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.9
    - ipywidgets >=7.5.0
    - ipygany >=0.5.0
    - xarray >=0.16.0

test:
  imports:
    - ipyfastscape
  commands:
    - pip check
  requires:
    - pip
    

about:
  home: https://github.com/fastscape-lem/ipyfastscape
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Interactive widgets for topographic data analysis and modelling in Jupyter notebooks

extra:
  recipe-maintainers:
    - benbovy
